apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterRoleIdentity
metadata:
  name: ${INFRA_ID}-installer
spec:
  allowedNamespaces:
    list:
    - openshift-cluster-api-guests
  roleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${INFRA_ID}-capa-installer
  sourceIdentityRef:
    kind: AWSClusterControllerIdentity
    name: default
