apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${INFRA_ID}
  namespace: openshift-cluster-api-guests
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: ${INFRA_ID}
    namespace: openshift-cluster-api
