apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachine
metadata:
  name: ${INFRA_ID}-master-2
  namespace: openshift-cluster-api-guests
  labels:
    cluster.x-k8s.io/control-plane: ""
spec: 
  failureDomain: ${REGION}c
  ignition:
    version: "3.2"
  uncompressedUserData: true
  iamInstanceProfile: ${INFRA_ID}-master-profile
  instanceType: m6i.xlarge
  ami:
    id: ami-0e3844336e31a8ed0
  subnet:
    filters:
    - name: tag:Name
      values:
      - ${INFRA_ID}-private-${REGION}c
  additionalTags:
    kubernetes.io/cluster/${INFRA_ID}: owned
  additionalSecurityGroups:
  - filters:
    - name: tag:Name
      values:
      - ${INFRA_ID}-ocp-controlplane
  rootVolume:
    size: 120
    type: gp3
    iops: 0
    encrypted: true
  sshKeyName: ""
