apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: ${INFRA_ID}-master-1
  namespace: openshift-cluster-api-guests
  labels:
    cluster.x-k8s.io/control-plane: ""
spec:
  bootstrap:
    dataSecretName: ${INFRA_ID}-master-user-data
  clusterName: ${INFRA_ID} 
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: AWSMachine
    name: ${INFRA_ID}-master-1
  failureDomain: ${REGION}b
